### ISSUE TITLE
Allow to check non-markdown sources

### ISSUE THREAD

**Issue by matthiasbeyer** [mgeisler/version-sync#17]
Hi,

just found your crate from your [post](https://users.rust-lang.org/t/whats-everyone-working-on-this-week-38-2017/12931/11?u=musicmatze) and I love it!

This is a feature request: In my project, I have some files which are not markdown, but contain version numbers. [Mainly the pandoc documentation header file](https://raw.githubusercontent.com/matthiasbeyer/imag/master/doc/src/00000.md). Therefor it would be awesome if there would be a possibility to also check plain text files.

I know, for most uses this is not what one wants, but for this specific use case it is of great importance... and I'd bet it is easy to implement!

**Comment by matthiasbeyer** [comment]
Maybe another note how I think this should work (just my 2ct):

I guess the best idea would be to check the file for the version pattern (as in `<number><dot><number><dot><number><whatever>`) and reject all strings that do not match the current version. Because parsing is not possible, of course, and checking whether the version string is _there_ does not make sense here, as we wouldn't check for its absence. :smile:

**Comment by mgeisler** [comment]
Hi Matthias, thanks for the feedback!

I would definitely like to support this! I've been thinking about adding a more free form check. Perhaps it could be something where you specify a regular expression with a placeholder?

The API might be as simple as a path and a regexp that selects the line you're interested in:
```rust
assert_version_updated!("my-pandoc-header.md", "version: $VERSION");
```
where `$VERSION` would be required to match the crate version number. I'm not sure `$VERSION` is the best syntax, especially since `$` is a special character in regexps :-)

**Comment by matthiasbeyer** [comment]
Well, you wouldn't even need to add the version in the string. Because you can aggregate that inside the macro, as you already do with the existing ones. Only a pattern would suffice I guess.
