### ISSUE TITLE
Possibility to check Cargo.toml files

### ISSUE THREAD

**Issue by matthiasbeyer** [mgeisler/version-sync#18]
And another feature request.

I'm working on a [project that contains a lot of sub-crates](https://github.com/matthiasbeyer/imag). Because it is my policy that all crates have the same version (0.4.0 upcoming), it would be awesome if one could check TOML files as well. Maybe not only the `Cargo.toml`, but all toml files.

This should be rather easy to implement as well, especially if you take advantage of my [toml-query](https://github.com/matthiasbeyer/toml-query) crate, so a user of your macro is able to specify the "path" how the version string is found in the toml file.

**Comment by mgeisler** [comment]
Okay, I think I see what you mean... :-) Where would the top-level version number be defined? It seems that the top-level Cargo.toml doesn't actually specify a version number. Would you define it via a file, for example?

I haven't tried using Cargo workspaces before — are the sub-crates compiled individually or are they compiled from the top-level with the `--all` flag? I suppose one can do both?

**Comment by matthiasbeyer** [comment]
> Where would the top-level version number be defined? 

I wouldn't even define it. Just verify that all version numbers are the same.

> I haven't tried using Cargo workspaces before — are the sub-crates compiled individually or are they compiled from the top-level with the --all flag? I suppose one can do both?

Both. But I guess your tool wouldn't even care about that. The way I would use this functionality would be: I would simply specify a build script that finds all `Cargo.toml` files and passes each of them to a checker that ensures that the version is correct.

I'm not sure whether that'd be the best approach, though.

**Comment by mgeisler** [comment]
I looked a little bit at this a while ago, but I didn't find an obvious way to do this at the time.

However, the new `assert_contains_regex!` macro in version 0.6 might help you do what you want. It certainly allows you to check `Cargo.toml` files now -- and you could thus conceive a unit test that finds the correct files and verifies their content.

Please let me know if you come up with something reusable. I'll close this issue in the mean time since it's not a feature I need (or fully understand) myself.
